# Generated by Django 3.1 on 2022-10-01 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20221001_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemeta',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
    ]
