# Generated by Django 3.1 on 2022-10-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_filemeta_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemeta',
            name='owner_first_name',
            field=models.CharField(db_index=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='filemeta',
            name='owner_last_name',
            field=models.CharField(db_index=True, max_length=35, null=True),
        ),
    ]
