# Generated by Django 4.1.2 on 2022-10-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20221002_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemeta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filemeta',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
